# Generated by Django 5.2.7 on 2025-12-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/company/'),
        ),
    ]
